Implement dynamic covering of IFTNodes with Instructions
TCS-Compilers/compiler pull request #111
Opened 2022-12-10 15:29 UTC by ignacy123

2022-12-11 16:33 UTC, JHodorHodor requested changes
Większość komenatrzy stylistycznych, najważniejsza rzecz, to żeby zsynchronizować się z PRem Rafała, żeby nam się wszystko później nie rozjechało za bardzo.

2022-12-11 16:33 UTC, JHodorHodor commented on app/src/main/kotlin/compiler/intermediate_form/DynamicCoveringBuilder.kt
> +            .associateWith { pattern -> matchPatternToParent(pattern)!!.first.sumOf { getMinimalCost(it) } + pattern.getCost() }
similar as above -- sounds like too many calls to the same thing

2022-12-11 16:33 UTC, JHodorHodor commented on app/src/main/kotlin/compiler/intermediate_form/DynamicCoveringBuilder.kt
> +        return coverGeneric({ pattern: InstructionPattern -> pattern.matchUnconditional(iftNode) }, iftNode)
```suggestion
        return coverGeneric({ pattern -> pattern.matchUnconditional(iftNode) }, iftNode)
```
nit

2022-12-11 16:33 UTC, JHodorHodor commented on app/src/main/kotlin/compiler/intermediate_form/DynamicCoveringBuilder.kt
> +    private fun calculateMinCosts(
`getBestPattern`?

2022-12-11 16:33 UTC, JHodorHodor commented on app/src/main/kotlin/compiler/intermediate_form/DynamicCoveringBuilder.kt
> +            val (remainingTrees, instructionConstructor) = patternChoices[iftNode]!!.matchValue(iftNode)!!
```suggestion
            val (uncoveredSubtrees, instructionConstructor) = patternChoices[iftNode]!!.matchValue(iftNode)!!
```
?

2022-12-11 16:33 UTC, JHodorHodor commented on app/src/main/kotlin/compiler/intermediate_form/DynamicCoveringBuilder.kt
> +            patternChoices: PatternChoices
On the other hand, `matchPatternToParent / matchValue` could be an argument to avoid repetition of the code for the parent.

2022-12-11 20:34 UTC, ignacy123 commented on app/src/main/kotlin/compiler/intermediate_form/InstructionSet.kt
> +        fun getCost(): Int = 1
This can be done later - might be a good idea for an extra task

2022-12-12 16:34 UTC, ignacy123 commented on app/src/main/kotlin/compiler/intermediate_form/DynamicCoveringBuilder.kt
> +            val (remainingTrees, instructionConstructor) = patternChoices[iftNode]!!.matchValue(iftNode)!!
Outdated cause of `Pattern.Result`

2022-12-12 16:42 UTC, ignacy123 commented
Do not merge, I switched base to make the diff easier to review.

2022-12-12 17:10 UTC, JHodorHodor commented on app/src/main/kotlin/compiler/intermediate_form/InstructionSet.kt
> +        fun getCost(): Int = 1
Ok

2022-12-12 17:14 UTC, JHodorHodor approved these changes

2022-12-13 09:02 UTC, merged