Parser e2e tests
TCS-Compilers/compiler pull request #38
Opened 2022-11-03 21:31 UTC by ggawryal

Tests are currently ignored. They'll be enabled after merging parser branches.

2022-11-06 00:02 UTC, rkilar reviewed
LGTM. I've confirmed that the tests pass with current parser PRs. Once those are merged and tests pass it will get approved.

2022-11-07 20:21 UTC, rkilar requested changes

2022-11-07 20:21 UTC, rkilar commented on app/src/test/kotlin/compiler/parser/integration_tests/ExpressionParsingTest.kt
> +    private val numParentheses = Production(numExpr, RegexParser.parseStringToRegex("\\(${addExpr}\\)"))
RegexParser was renamed to LexerRegexParser

2022-11-07 20:21 UTC, rkilar commented on app/src/test/kotlin/compiler/parser/integration_tests/NonLL1Grammar.kt
> +    private val cToac = Production('C', RegexParser.parseStringToRegex("ac"))
Same here

2022-11-08 02:36 UTC, ggawryal commented
Fixed

2022-11-08 09:20 UTC, rkilar approved these changes

2022-11-08 09:20 UTC, merged