Parser table
TCS-Compilers/compiler pull request #39
Opened 2022-11-03 21:42 UTC by woocash2

This is a parser table pull request

2022-11-05 17:50 UTC, rkilar requested changes
The code looks to be correct. I left some small stylistic suggestions.

2022-11-05 17:50 UTC, rkilar commented on app/src/main/kotlin/compiler/parser/analysis/GrammarAnalysis.kt
> +        return firstPlus
I feel like this function could be shorter and more readable with something like `return grammar.getSymbols().associateWith` and `union` to closer match the mathematical definition.

2022-11-06 16:51 UTC, bebidek commented
I love the commit message "Shut up, ktlint".

2022-11-07 19:24 UTC, rkilar approved these changes

2022-11-07 20:20 UTC, merged