Name resolution errors e2e tests
TCS-Compilers/compiler pull request #45
Opened 2022-11-10 14:40 UTC by JHodorHodor

All new tests have `@Ignore` annotation!

2022-11-11 17:14 UTC, ignacy123 commented
I think it is also worth adding the following test case:
```
x = 15
zm x: Liczba = 17
```
to ensure we don't mess up the order somewhere. Maybe the same idea can be used for other scenarios?

2022-11-12 13:58 UTC, kamgal00 requested changes
Testy są dobrze napisane i rozpatrują wszystkie przypadki, brakuje mi jedynie kilku testów dla parametrów funkcji.

2022-11-12 13:58 UTC, kamgal00 commented on app/src/test/kotlin/compiler/e2e/NameResolutionErrorsTest.kt
> +                        zm x: Liczba = x
I think it should be `zm x: Liczba = g`

2022-11-12 13:58 UTC, kamgal00 commented on app/src/test/kotlin/compiler/e2e/NameResolutionErrorsTest.kt
> +    // I'm not 100% sure if the next two tests make sense
In my opinion, they make sense - our language doesn't support using functions as variables at this point.

2022-11-12 13:58 UTC, kamgal00 commented on app/src/test/kotlin/compiler/e2e/NameResolutionErrorsTest.kt
> +    }
Could you please add some tests for function parameters? We could test, for example, name conflicts (between two parameters and between a parameter and a variable), treating parameters as callables, using parameters outside function scope, and maybe using undefined variables/functions as default parameter values:
```
czynność f(x: Liczba = y) {}
czynność f(x: Liczba = f()) {}
```

2022-11-12 13:58 UTC, kamgal00 commented on app/src/test/kotlin/compiler/e2e/NameResolutionErrorsTest.kt
> +            Diagnostic.NameResolutionErrors.FunctionIsNotVariable::class
This test is probably redundant - the previous one already tests if `g` is a correct expression

2022-11-13 22:47 UTC, kamgal00 approved these changes

2022-11-14 09:39 UTC, merged