Create tests for expression to cfg conversion
TCS-Compilers/compiler pull request #85
Opened 2022-11-27 20:38 UTC by kamgal00

2022-11-28 22:36 UTC, ignacy123 requested changes
The tests themselves seem quite exhaustive already, but I'd suggest adding:
 - some tests for all basic literals (literals and unary operations). They might be helpful if there will be some problems with testing framework/CFG calculations very early on.
 - some complex tests with functions not affecting variables at the same level. This is to ensure that the CFG builder can take advantage of that and allows for parallel processing.

Most of my remarks are related to style and decreasing line count. Some of them are also trying to prevent code duplication with other branches before it occurs - please try to incorporate these suggestions.
I am a fan of your usage of `infix` notation, really helps with readability :+1:

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +                finalCallGraph[nameToFunMap[name]!!] = referenceHashSet
```suggestion
                finalCallGraph[nameToFunMap[name]!!] = referenceSetOf(nameToFunMap[name]!!)
```

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            return ControlFlow.createGraphForExpression(expr, targetVariable, currentFunction, nameResolution, variableProperties, finalCallGraph, functionDetailsGenerators, argumentResolution)
Please split this into more lines

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            }
```suggestion
            functionDetailsGenerators = (nameToFunMap.values union setOf(currentFunction)).associate{ it to TestFunctionDetailsGenerator(it)}
```

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            }
This can be simplified to two `associate`s (example usage of `associate` below)

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            for (entry in funToAffectedVar) {
```suggestion
            for ((name, variables) in funToAffectedVar) {
```

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            for (entry in funToAffectedVar) {
Also, I think `. forEach { }` construct might be better suited here

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +        fun <T> ReferenceHashMap<T, T>.isBijection(a: T, b: T): Boolean {
```suggestion
        fun <T> ReferenceHashMap<T, T>.ensurePairSymmetrical(a: T, b: T): Boolean {
```
The previous name suggests this function has no side-effects

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +                    }
```suggestion
         (this.args zip iftNode.args).forEach { if // logic }
```

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            if (!(this.treeRoots[i] hasSameStructureAs cfg.treeRoots[i])) return false
We can `zip` here as well

2022-11-28 22:36 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +        val cfg = context.createCfg( //   x + ( g( a + f() , b ) + ( ( b + x ) + ( h() ? x : y ) ) )
```suggestion
        val cfg = context.createCfg( //   x + ( g( a + f() , b ) + ( ( b + x ) + ( h() ? x : y ) ) ) f -> x, h -> b
```

2022-11-29 13:11 UTC, bebidek commented
Should be able to auto-merge to master now.

2022-11-29 19:25 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +            }
won't work cause reference maps

2022-11-29 19:33 UTC, ignacy123 requested changes
I left some comments in the [old PR](https://github.com/TCS-Compilers/compiler/pull/84), which got merged before my approval.
Please address them here, as this is the only place where this can be done now.

2022-11-29 19:33 UTC, ignacy123 commented on app/src/test/kotlin/compiler/intermediate_form/ExpressionControlFlowTest.kt
> +        println(basic)
This shouldn't be here I think :stuck_out_tongue:

2022-11-30 08:31 UTC, ignacy123 approved these changes

2022-11-30 14:36 UTC, merged